name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action
        runL: touch .env.local
          echo ABLY_API_KEY=${{ secrets.ABLY_API_KEY }} >> .env.local
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env.local
          echo IMGUR_CLIENT_ID=${{ secrets.IMGUR_CLIENT_ID }} >> .env.local
        with:
          build: npm run build
          start: npm start
